version: '3'
services:
  web:
    build: .
    restart: always
    networks:
    - web
    - db
  db:
    image: "mongo:3-jessie"
    restart: always
    volumes:
    - data:
    networks:
    - db

volumes:
  data:

networks:
  web:
    internal: true
  db:
    internal: true
